site_name: Filmmaker Plugin Documentation
site_url: https://tbj-team.github.io/filmmaker-plugin/
repo_name: TBJ-Team/filmmaker-plugin
repo_url: https://github.com/TBJ-Team/filmmaker-plugin

theme:
  name: material
  palette:
    primary: 'Yellow'
    accent: 'Yellow'

nav:
  - Home: index.md
  - Guide:
    - Basic Animation: guide/b_animation.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences