site_name: Filmmaker
site_url: https://gyrolabs.github.io/filmmaker/
site_description: >-
  Create fluid animation with Filmmaker, the animation suite produced
  by Gyro Laboratories. Explore many different possibilities,
  completely free of charge.

repo_name: GyroLabs/filmmaker
repo_url: https://github.com/GyroLabs/filmmaker

theme:
  name: material

  features:
    - navigation.tabs
    - navigation.instant

  palette:
    scheme: slate
    primary: blue
    accent: blue

  icon:
    repo: fontawesome/brands/git-alt

nav:
  - Home: index.md
  - Guide:
    - Introduction: guide/introduction.md
    - Basic Animation: guide/b_animation.md
  - Reference:
    - The Graph Editor: reference/graph_editor.md
  - Contributing:
    - Code Contributions: contributing/contributing.md
    - Animation Contributions: contributing/animations.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - meta

plugins:
  - search
