site_name: Filmmaker
site_url: https://gyrolabs.github.io/filmmaker/
site_author: Gyro Laboratories
site_description: >-
  Create fluid animation with Filmmaker, the animation suite produced
  by Gyro Laboratories. Explore many different possibilities,
  completely free of charge.

repo_name: GyroLabs/filmmaker
repo_url: https://github.com/GyroLabs/filmmaker

copyright: Roblox are trademarks of Roblox Corporation or its affiliates in the United States and/or other countries.

theme:
  name: material
  custom_dir: overrides

  features:
    - navigation.tabs

  palette:
    scheme: default
    primary: blue
    accent: blue

  icon:
    repo: fontawesome/brands/git-alt

nav:
  - Home: index.md
  - Guide:
    - Introduction: guide/introduction.md
    - Installation: guide/installation.md
    - Basic Animation: guide/b_animation.md
    - Advanced Animation: guide/a_animation.md
  - Reference:
    - The Graph Editor: reference/graph_editor.md
    - The Project Editor: reference/project_editor.md
  - Contributing:
    - Code Contributions: contributing/contributing.md
    - Animation Contributions: contributing/animations.md
  - API:
      - api/index.html

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed
  - pymdownx.superfences

plugins:
  - search
