site_name: Filmmaker
site_url: https://tbj-team.github.io/filmmaker/
repo_name: TBJ-Team/filmmaker
repo_url: https://github.com/TBJ-Team/filmmaker

theme:
  name: material
  palette:
    primary: 'Red'
    accent: 'Red'

nav:
  - Home: index.md
  - Guide:
    - Basic Animation: guide/b_animation.md
  - Contributing:
    - Code Contributions: contributing/contributing.md
    - Animation Contributions: contributing/animations.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences