name: CI

on:
  push:
    branches:
    - master

  pull_request:
    branches:
    - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - uses: Roblox/setup-foreman@v1
      with:
        version: "^1.0.0"
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Report tool versions
      run: selene --version

    - name: Test
      run: |
        selene src